---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
    - enable_repo

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
    - deploy_haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - deploy_tomcat

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
 
  roles:
    - deploy_postgres
